import type {
  Article,
  Center,
  CenterReview,
  ClassIntake,
  Teacher,
  Company,
  JobOrder,
  CommunityPost,
  VerificationRequest,
  ReportFlag,
  PricingPlan,
} from "@/types";

export const heroStats = [
  { label: "Việc làm đang tuyển", value: "2.450+" },
  { label: "Trung tâm đối tác", value: "320+" },
  { label: "Nhà tuyển dụng Đức", value: "1.250+" },
  { label: "Học viên đã tham gia", value: "18.000+" },
];

export const articles: Article[] = [
  {
    id: "a1",
    title: "Nhu cầu nhân lực ngành điều dưỡng tại Đức tiếp tục tăng mạnh",
    slug: "nhu-cau-nhan-luc-dieu-duong-duc-tang-manh",
    excerpt:
      "Báo cáo mới nhất từ Bộ Lao động Đức cho thấy thiếu hụt 200.000 vị trí điều dưỡng đến năm 2030, tạo cơ hội lớn cho học viên Việt Nam.",
    category: "Thị trường",
    cover_image_url:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200",
    author: "Ban biên tập",
    published_at: "2026-04-22T08:00:00Z",
    read_time: 6,
    is_sponsored: false,
    views: 1200,
    comments: 45,
    tags: ["điều dưỡng", "thị trường", "2026"],
  },
  {
    id: "a2",
    title: "Visa Ausbildung 2026: Những thay đổi quan trọng bạn cần biết",
    slug: "visa-ausbildung-2026-thay-doi",
    excerpt:
      "Quy trình xin visa Ausbildung được rút gọn, hồ sơ tài chính giảm tải, và yêu cầu tiếng Đức linh hoạt hơn cho một số ngành.",
    category: "Chính sách",
    cover_image_url:
      "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=1200",
    author: "Phan Minh Anh",
    published_at: "2026-04-20T08:00:00Z",
    read_time: 8,
    is_sponsored: false,
    views: 980,
    comments: 32,
    tags: ["visa", "chính sách"],
  },
  {
    id: "a3",
    title: "Bí quyết học tiếng Đức nhanh và hiệu quả cùng DeutschAkademie",
    slug: "bi-quyet-hoc-tieng-duc-nhanh-deutschakademie",
    excerpt:
      "Phương pháp 4-step Listening – Speaking – Writing – Reading kết hợp lớp học live với coach 1-1 đang thay đổi cách học tiếng Đức tại Việt Nam.",
    category: "Tài trợ",
    cover_image_url:
      "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1200",
    author: "DeutschAkademie",
    published_at: "2026-04-18T08:00:00Z",
    read_time: 5,
    is_sponsored: true,
    views: 3271,
    comments: 0,
    tags: ["tiếng đức", "phương pháp"],
  },
  {
    id: "a4",
    title: "Top 10 ngành có cơ hội việc làm cao nhất tại Đức năm 2026",
    slug: "top-10-nganh-viec-lam-cao-nhat-2026",
    excerpt:
      "Từ điều dưỡng, IT, đến cơ điện tử và nhà hàng-khách sạn — danh sách ngành nóng được cập nhật theo dữ liệu BA Statistik mới nhất.",
    category: "Thị trường",
    cover_image_url:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200",
    author: "Trần Đức Nam",
    published_at: "2026-04-15T08:00:00Z",
    read_time: 7,
    is_sponsored: false,
    views: 2104,
    comments: 67,
    tags: ["thị trường", "ngành nghề"],
  },
  {
    id: "a5",
    title: "Học bổng Hans-Seidel 2026 cho học viên Ausbildung Việt Nam",
    slug: "hoc-bong-hans-seidel-2026",
    excerpt:
      "Quỹ Hans-Seidel mở học bổng 2.500 EUR/năm cho 50 học viên Việt Nam có thành tích B1 trở lên, deadline 30/06/2026.",
    category: "Học bổng",
    cover_image_url:
      "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200",
    author: "Nguyễn Minh Anh",
    published_at: "2026-04-12T08:00:00Z",
    read_time: 4,
    is_sponsored: false,
    views: 1543,
    comments: 22,
    tags: ["học bổng", "tài chính"],
  },
  {
    id: "a6",
    title: "Kinh nghiệm phỏng vấn đơn nhà hàng – khách sạn tại Bayern",
    slug: "kinh-nghiem-phong-van-nha-hang-bayern",
    excerpt:
      "Tổng hợp 15 câu hỏi thường gặp, mẹo trả lời và checklist chuẩn bị từ học viên đã trúng tuyển tại các hệ thống khách sạn 4-5 sao Munich.",
    category: "Kinh nghiệm",
    cover_image_url:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200",
    author: "Lê Thị Hương",
    published_at: "2026-04-10T08:00:00Z",
    read_time: 9,
    is_sponsored: false,
    views: 1820,
    comments: 54,
    tags: ["phỏng vấn", "nhà hàng"],
  },
  {
    id: "a7",
    title: "Hướng dẫn chuẩn bị hồ sơ visa Ausbildung từ A đến Z",
    slug: "huong-dan-ho-so-visa-ausbildung",
    excerpt:
      "Checklist 23 đầu mục giấy tờ, biểu mẫu kèm tiếng Việt + tiếng Đức và quy trình hợp pháp hóa lãnh sự rút gọn.",
    category: "Chính sách",
    cover_image_url:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200",
    author: "Ban biên tập",
    published_at: "2026-04-08T08:00:00Z",
    read_time: 12,
    is_sponsored: false,
    views: 4280,
    comments: 89,
    tags: ["visa", "hồ sơ"],
  },
  {
    id: "a8",
    title: "5 lý do chọn học tiếng Đức với trung tâm được xác minh",
    slug: "5-ly-do-trung-tam-xac-minh",
    excerpt:
      "Trung tâm được Ausbildung Hub Vietnam xác minh phải đáp ứng 12 tiêu chí về giáo viên, cơ sở vật chất và minh bạch học phí.",
    category: "Kinh nghiệm",
    cover_image_url:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200",
    author: "Ban biên tập",
    published_at: "2026-04-05T08:00:00Z",
    read_time: 6,
    is_sponsored: false,
    views: 1430,
    comments: 38,
    tags: ["xác minh", "trung tâm"],
  },
];

export const centers: Center[] = [
  {
    id: "c1",
    name: "DeutschAkademie Hà Nội",
    slug: "deutschakademie-ha-noi",
    logo_url: "https://logo.clearbit.com/deutschakademie.de",
    city: "Hà Nội",
    address: "12 Tràng Tiền, Hoàn Kiếm, Hà Nội",
    website: "https://deutschakademie.vn",
    phone: "024 3936 1234",
    description:
      "Trung tâm Đức ngữ hàng đầu với hơn 15 năm kinh nghiệm đào tạo và chuẩn châu Âu CEFR. Đội ngũ giáo viên bản ngữ và phương pháp giao tiếp thực tiễn.",
    german_levels: ["A1", "A2", "B1", "B2"],
    tuition_min: 5000000,
    tuition_max: 12000000,
    verification_status: "verified",
    rating_avg: 4.9,
    review_count: 128,
    next_intake_date: "2026-05-15",
    branches: ["Hà Nội", "Hồ Chí Minh"],
    highlights: ["Giáo viên bản ngữ", "Lớp 12 học viên", "Cam kết đầu ra B1"],
  },
  {
    id: "c2",
    name: "VIETGERMANY – HCM",
    slug: "vietgermany-hcm",
    logo_url: "https://ui-avatars.com/api/?name=VG&background=3b82f6&color=fff",
    city: "Hồ Chí Minh",
    address: "88 Nguyễn Du, Quận 1, TP HCM",
    website: "https://vietgermany.vn",
    phone: "028 3829 5678",
    description:
      "Đối tác chính thức của Goethe-Institut, chuyên đào tạo học viên đi du học nghề điều dưỡng và nhà hàng tại Đức.",
    german_levels: ["A1", "A2", "B1", "B2"],
    tuition_min: 4500000,
    tuition_max: 11500000,
    verification_status: "verified",
    rating_avg: 4.8,
    review_count: 96,
    next_intake_date: "2026-05-20",
    highlights: ["Đối tác Goethe", "Học bổng 30%", "Tư vấn miễn phí"],
  },
  {
    id: "c3",
    name: "EuroSkills Vietnam – Đà Nẵng",
    slug: "euroskills-vietnam-da-nang",
    logo_url: "https://ui-avatars.com/api/?name=ES&background=22d3ee&color=000",
    city: "Đà Nẵng",
    address: "45 Bạch Đằng, Hải Châu, Đà Nẵng",
    website: "https://euroskills.vn",
    phone: "0236 3888 234",
    description:
      "Mô hình lớp nhỏ kết hợp luyện thi ÖSD/Goethe, hỗ trợ trọn gói từ tiếng Đức đến hồ sơ visa.",
    german_levels: ["A1", "A2", "B1"],
    tuition_min: 4000000,
    tuition_max: 10000000,
    verification_status: "verified",
    rating_avg: 4.7,
    review_count: 86,
    next_intake_date: "2026-06-01",
  },
  {
    id: "c4",
    name: "EduGo Germany – Hải Phòng",
    slug: "edugo-germany-hai-phong",
    logo_url: "https://ui-avatars.com/api/?name=EG&background=8b5cf6&color=fff",
    city: "Hải Phòng",
    address: "123 Lạch Tray, Ngô Quyền, Hải Phòng",
    website: "https://edugo.vn",
    phone: "0225 3888 999",
    description:
      "Chuyên đào tạo tiếng Đức và tư vấn du học nghề, ưu tiên ngành cơ điện tử và IT.",
    german_levels: ["A1", "A2", "B1"],
    tuition_min: 3800000,
    tuition_max: 9500000,
    verification_status: "verified",
    rating_avg: 4.6,
    review_count: 73,
    next_intake_date: "2026-05-25",
  },
  {
    id: "c5",
    name: "Hanoi Deutsch Center",
    slug: "hanoi-deutsch-center",
    logo_url: "https://ui-avatars.com/api/?name=HD&background=06b6d4&color=fff",
    city: "Hà Nội",
    description:
      "Trung tâm tiếng Đức tập trung vào lớp luyện thi B1-B2, cam kết đầu ra trong 8 tháng.",
    german_levels: ["A2", "B1", "B2"],
    tuition_min: 5500000,
    tuition_max: 13000000,
    verification_status: "verified",
    rating_avg: 4.5,
    review_count: 64,
    next_intake_date: "2026-06-10",
  },
  {
    id: "c6",
    name: "Berliner Tor Sài Gòn",
    slug: "berliner-tor-sai-gon",
    logo_url: "https://ui-avatars.com/api/?name=BT&background=facc15&color=000",
    city: "Hồ Chí Minh",
    description:
      "Phương pháp học giao tiếp 1-1 với giáo viên bản ngữ, tập trung khả năng sử dụng tiếng Đức trong môi trường làm việc.",
    german_levels: ["A1", "A2", "B1", "B2"],
    tuition_min: 6000000,
    tuition_max: 14000000,
    verification_status: "pending",
    rating_avg: 4.4,
    review_count: 52,
    next_intake_date: "2026-06-05",
  },
  {
    id: "c7",
    name: "Goethe Hub Cần Thơ",
    slug: "goethe-hub-can-tho",
    logo_url: "https://ui-avatars.com/api/?name=GH&background=22c55e&color=fff",
    city: "Cần Thơ",
    description:
      "Trung tâm tiếng Đức đầu tiên tại miền Tây, chuyên đào tạo học viên ngành điều dưỡng và nhà hàng.",
    german_levels: ["A1", "A2", "B1"],
    tuition_min: 3500000,
    tuition_max: 8500000,
    verification_status: "verified",
    rating_avg: 4.5,
    review_count: 41,
    next_intake_date: "2026-06-15",
  },
  {
    id: "c8",
    name: "Bremen Akademie Vinh",
    slug: "bremen-akademie-vinh",
    logo_url: "https://ui-avatars.com/api/?name=BA&background=ef4444&color=fff",
    city: "Vinh",
    description:
      "Trung tâm đào tạo tiếng Đức kết hợp định hướng nghề nghiệp, hỗ trợ trọn gói visa cho học viên Bắc Trung Bộ.",
    german_levels: ["A1", "A2", "B1"],
    tuition_min: 3200000,
    tuition_max: 8000000,
    verification_status: "verified",
    rating_avg: 4.6,
    review_count: 35,
    next_intake_date: "2026-06-20",
  },
];

export const centerReviews: CenterReview[] = [
  {
    id: "r1",
    center_id: "c1",
    reviewer_name: "Nguyễn Minh Anh",
    reviewer_role: "Học viên B1",
    rating: 5,
    title: "Giáo viên cực kỳ tận tâm",
    body:
      "Học 6 tháng đã đạt B1, giáo viên chữa bài rất kỹ và lớp ít bạn nên được giao tiếp nhiều.",
    created_at: "2026-04-15T10:00:00Z",
    status: "approved",
  },
  {
    id: "r2",
    center_id: "c1",
    reviewer_name: "Trần Đức Nam",
    reviewer_role: "Cựu học viên",
    rating: 5,
    title: "Hỗ trợ visa rất chi tiết",
    body:
      "Trung tâm đã hỗ trợ mình từ A đến Z hồ sơ visa Ausbildung, hiện đang làm việc tại Berlin.",
    created_at: "2026-04-10T10:00:00Z",
    status: "approved",
  },
  {
    id: "r3",
    center_id: "c1",
    reviewer_name: "Lê Hồng Linh",
    reviewer_role: "Học viên A2",
    rating: 4,
    title: "Cơ sở vật chất tốt",
    body:
      "Phòng học hiện đại, có thiết bị nghe nói chuẩn châu Âu. Mong có thêm lớp tối cuối tuần.",
    created_at: "2026-04-05T10:00:00Z",
    status: "approved",
  },
];

export const classIntakes: ClassIntake[] = [
  {
    id: "ci1",
    center_id: "c1",
    level: "A1",
    start_date: "2026-05-15",
    schedule: "Tối T2/T4/T6 — 18:30-20:30",
    seats_left: 6,
    tuition: 5000000,
  },
  {
    id: "ci2",
    center_id: "c1",
    level: "B1",
    start_date: "2026-05-20",
    schedule: "Sáng T3/T5/T7 — 8:00-10:00",
    seats_left: 3,
    tuition: 9500000,
  },
  {
    id: "ci3",
    center_id: "c1",
    level: "B2",
    start_date: "2026-06-01",
    schedule: "Tối T2/T4/T6 — 19:00-21:00",
    seats_left: 8,
    tuition: 12000000,
  },
];

export const teachers: Teacher[] = [
  {
    id: "t1",
    center_id: "c1",
    full_name: "Dr. Maria Schmidt",
    level: "C1",
    years_exp: 12,
    avatar_url: "https://ui-avatars.com/api/?name=Maria+Schmidt&background=22d3ee",
    bio: "Tiến sĩ Ngôn ngữ học từ ĐH Heidelberg, 12 năm dạy tiếng Đức tại Việt Nam.",
  },
  {
    id: "t2",
    center_id: "c1",
    full_name: "Phạm Thanh Hà",
    level: "C2",
    years_exp: 8,
    avatar_url: "https://ui-avatars.com/api/?name=Thanh+Ha&background=8b5cf6",
    bio: "Cựu sinh viên ĐH München, chuyên luyện thi B2/C1.",
  },
];

export const companies: Company[] = [
  {
    id: "co1",
    name: "Siemens AG",
    slug: "siemens",
    logo_url: "https://logo.clearbit.com/siemens.com",
    industry: "Cơ điện tử / Tự động hóa",
    city: "Munich",
    state: "Bayern",
    country: "Đức",
    website: "https://siemens.com",
    description:
      "Tập đoàn công nghệ và công nghiệp toàn cầu, tuyển dụng Ausbildung kỹ thuật viên cơ điện tử và IT hàng năm.",
    verification_status: "verified",
    rating_avg: 4.9,
    job_count: 28,
    satisfaction_rate: 95,
  },
  {
    id: "co2",
    name: "Robert Bosch GmbH",
    slug: "bosch",
    logo_url: "https://logo.clearbit.com/bosch.com",
    industry: "Cơ khí / Ô tô",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    country: "Đức",
    description:
      "Nhà sản xuất thiết bị công nghiệp và phụ tùng ô tô lớn nhất thế giới, mở rộng tuyển dụng Việt Nam từ 2024.",
    verification_status: "verified",
    rating_avg: 4.8,
    job_count: 22,
    satisfaction_rate: 93,
  },
  {
    id: "co3",
    name: "B. Braun Melsungen",
    slug: "b-braun",
    logo_url: "https://logo.clearbit.com/bbraun.com",
    industry: "Y tế / Thiết bị y tế",
    city: "Melsungen",
    state: "Hessen",
    country: "Đức",
    description:
      "Tập đoàn y tế hàng đầu châu Âu, chuyên tuyển điều dưỡng viên và kỹ thuật viên y tế.",
    verification_status: "verified",
    rating_avg: 4.7,
    job_count: 35,
    satisfaction_rate: 92,
  },
  {
    id: "co4",
    name: "Lidl Stiftung & Co. KG",
    slug: "lidl",
    logo_url: "https://logo.clearbit.com/lidl.de",
    industry: "Bán lẻ",
    city: "Neckarsulm",
    state: "Baden-Württemberg",
    country: "Đức",
    description:
      "Chuỗi siêu thị lớn nhất nước Đức, đào tạo Ausbildung quản lý cửa hàng và logistics.",
    verification_status: "verified",
    rating_avg: 4.5,
    job_count: 41,
    satisfaction_rate: 88,
  },
  {
    id: "co5",
    name: "K&S Gruppe",
    slug: "ks-gruppe",
    logo_url: "https://ui-avatars.com/api/?name=KS&background=3b82f6&color=fff",
    industry: "Y tế / Điều dưỡng",
    city: "Frankfurt",
    state: "Hessen",
    country: "Đức",
    description:
      "Hệ thống bệnh viện và viện dưỡng lão lớn, chuyên tuyển điều dưỡng viên Việt Nam.",
    verification_status: "verified",
    rating_avg: 4.6,
    job_count: 52,
    satisfaction_rate: 90,
  },
  {
    id: "co6",
    name: "BMW Group",
    slug: "bmw",
    logo_url: "https://logo.clearbit.com/bmw.com",
    industry: "Ô tô",
    city: "Munich",
    state: "Bayern",
    country: "Đức",
    description:
      "Tập đoàn xe hơi cao cấp, tuyển dụng Ausbildung kỹ thuật viên cơ khí, điện tử ô tô.",
    verification_status: "verified",
    rating_avg: 4.8,
    job_count: 18,
    satisfaction_rate: 94,
  },
  {
    id: "co7",
    name: "Charité Berlin",
    slug: "charite-berlin",
    logo_url: "https://ui-avatars.com/api/?name=CB&background=ef4444&color=fff",
    industry: "Y tế / Bệnh viện",
    city: "Berlin",
    state: "Berlin",
    country: "Đức",
    description:
      "Bệnh viện đại học lớn nhất châu Âu, đào tạo điều dưỡng theo chuẩn WHO.",
    verification_status: "verified",
    rating_avg: 4.9,
    job_count: 30,
    satisfaction_rate: 96,
  },
  {
    id: "co8",
    name: "Marriott Hotels Germany",
    slug: "marriott-germany",
    logo_url: "https://logo.clearbit.com/marriott.com",
    industry: "Nhà hàng – Khách sạn",
    city: "Frankfurt",
    state: "Hessen",
    country: "Đức",
    description:
      "Chuỗi khách sạn 5 sao quốc tế, tuyển Ausbildung F&B và quản lý khách sạn.",
    verification_status: "verified",
    rating_avg: 4.6,
    job_count: 24,
    satisfaction_rate: 89,
  },
];

export const jobOrders: JobOrder[] = [
  {
    id: "j1",
    company_id: "co7",
    company_name: "Charité Berlin",
    company_logo: "https://ui-avatars.com/api/?name=CB&background=ef4444&color=fff",
    title: "Điều dưỡng viên (Pflegefachfrau/-mann)",
    slug: "dieu-duong-vien-charite-berlin",
    occupation: "Điều dưỡng",
    training_type: "Dual",
    city: "Berlin",
    state: "Berlin",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1250,
    monthly_allowance_max: 1450,
    start_date: "2026-09-01",
    interview_date: "2026-06-15",
    deadline: "2026-06-01",
    description:
      "Chương trình Ausbildung 3 năm tại bệnh viện đại học Charité, đào tạo điều dưỡng đa khoa. Học viên được học vừa làm tại các khoa nội trú, ngoại khoa và ICU.",
    requirements: ["Tiếng Đức B1 trở lên", "Tốt nghiệp THPT", "Đam mê chăm sóc sức khỏe"],
    benefits: [
      "Lương Ausbildung 1.250–1.450 EUR/tháng",
      "Hỗ trợ nhà ở 200 EUR/tháng",
      "Bảo hiểm y tế đầy đủ",
      "Cơ hội ở lại làm việc 5 năm",
    ],
    status: "open",
    verification_status: "verified",
    is_featured: true,
    created_at: "2026-04-20T08:00:00Z",
  },
  {
    id: "j2",
    company_id: "co1",
    company_name: "Siemens AG",
    company_logo: "https://logo.clearbit.com/siemens.com",
    title: "Kỹ thuật viên cơ điện tử (Mechatroniker)",
    slug: "ky-thuat-vien-co-dien-tu-siemens",
    occupation: "Cơ điện tử",
    training_type: "Dual",
    city: "Munich",
    state: "Bayern",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT, ưu tiên có nền tảng kỹ thuật",
    monthly_allowance_min: 1150,
    monthly_allowance_max: 1350,
    start_date: "2026-09-01",
    interview_date: "2026-06-20",
    deadline: "2026-05-30",
    description:
      "Chương trình Ausbildung 3.5 năm với Siemens Technik Akademie tại Munich. Học viên được làm việc với robot công nghiệp, hệ thống PLC và automation.",
    requirements: ["Tiếng Đức B1", "Toán/Lý khá", "Sức khỏe tốt"],
    benefits: ["Lương 1.150–1.350 EUR", "Học phí miễn phí", "Cơ hội thăng tiến rõ ràng"],
    status: "open",
    verification_status: "verified",
    is_featured: true,
    created_at: "2026-04-19T08:00:00Z",
  },
  {
    id: "j3",
    company_id: "co8",
    company_name: "Marriott Hotels Germany",
    company_logo: "https://logo.clearbit.com/marriott.com",
    title: "Nhà hàng – Khách sạn (Hotelfachfrau/-mann)",
    slug: "nha-hang-khach-san-marriott-stuttgart",
    occupation: "Nhà hàng-Khách sạn",
    training_type: "Dual",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1050,
    monthly_allowance_max: 1250,
    start_date: "2026-08-15",
    interview_date: "2026-06-10",
    deadline: "2026-05-28",
    description:
      "Chương trình Ausbildung 3 năm tại Marriott Stuttgart, được luân chuyển qua các bộ phận F&B, lễ tân, phòng và sự kiện.",
    requirements: ["Tiếng Đức B1", "Khả năng giao tiếp tốt", "Ngoại hình ưa nhìn"],
    benefits: ["Lương 1.050–1.250 EUR", "Bữa ăn miễn phí", "Đồng phục cấp"],
    status: "open",
    verification_status: "verified",
    is_featured: true,
    created_at: "2026-04-18T08:00:00Z",
  },
  {
    id: "j4",
    company_id: "co4",
    company_name: "Lidl Stiftung & Co. KG",
    company_logo: "https://logo.clearbit.com/lidl.de",
    title: "Bán lẻ (Kaufmann/-frau im Einzelhandel)",
    slug: "ban-le-lidl-hamburg",
    occupation: "Bán lẻ",
    training_type: "Dual",
    city: "Hamburg",
    state: "Hamburg",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1100,
    monthly_allowance_max: 1300,
    start_date: "2026-09-01",
    interview_date: "2026-06-25",
    deadline: "2026-06-05",
    description:
      "Chương trình quản lý cửa hàng, tổ chức kho, quan hệ khách hàng và marketing tại hệ thống Lidl khu vực Hamburg.",
    requirements: ["Tiếng Đức B1", "Năng động", "Có khả năng giao tiếp"],
    benefits: ["Lương 1.100–1.300 EUR", "Thưởng năng suất", "Lộ trình thăng tiến"],
    status: "open",
    verification_status: "verified",
    is_featured: true,
    created_at: "2026-04-17T08:00:00Z",
  },
  {
    id: "j5",
    company_id: "co5",
    company_name: "K&S Gruppe",
    company_logo: "https://ui-avatars.com/api/?name=KS&background=3b82f6&color=fff",
    title: "Điều dưỡng viên cao tuổi (Altenpflege)",
    slug: "dieu-duong-cao-tuoi-ks-frankfurt",
    occupation: "Điều dưỡng",
    training_type: "Dual",
    city: "Frankfurt",
    state: "Hessen",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1200,
    monthly_allowance_max: 1400,
    start_date: "2026-10-01",
    interview_date: "2026-07-05",
    deadline: "2026-06-20",
    description:
      "Chăm sóc người cao tuổi tại các viện K&S khu vực Frankfurt – Mainz, đào tạo song song lý thuyết và thực hành.",
    requirements: ["Tiếng Đức B1", "Tâm lý vững vàng", "Yêu thích ngành chăm sóc"],
    benefits: ["Lương 1.200–1.400 EUR", "Hỗ trợ nhà ở", "Bảo hiểm đầy đủ"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-16T08:00:00Z",
  },
  {
    id: "j6",
    company_id: "co1",
    company_name: "Siemens AG",
    company_logo: "https://logo.clearbit.com/siemens.com",
    title: "IT System Administrator",
    slug: "it-system-admin-siemens-munich",
    occupation: "IT",
    training_type: "Dual",
    city: "Munich",
    state: "Bayern",
    german_level_required: "B2",
    education_required: "Tốt nghiệp THPT, ưu tiên có nền tảng CNTT",
    monthly_allowance_min: 1250,
    monthly_allowance_max: 1450,
    start_date: "2026-09-01",
    interview_date: "2026-06-30",
    deadline: "2026-06-10",
    description:
      "Quản trị hệ thống IT cho Siemens — Linux, Windows Server, network. Học viên được tham gia các dự án automation thực tế.",
    requirements: ["Tiếng Đức B2", "Kiến thức Linux/Windows cơ bản", "Tư duy logic"],
    benefits: ["Lương 1.250–1.450 EUR", "Học bổng C1", "Cơ hội ở lại"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-15T08:00:00Z",
  },
  {
    id: "j7",
    company_id: "co3",
    company_name: "B. Braun Melsungen",
    company_logo: "https://logo.clearbit.com/bbraun.com",
    title: "Kỹ thuật viên thiết bị y tế",
    slug: "ky-thuat-vien-thiet-bi-y-te-bbraun",
    occupation: "Y tế kỹ thuật",
    training_type: "Dual",
    city: "Melsungen",
    state: "Hessen",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1100,
    monthly_allowance_max: 1300,
    start_date: "2026-09-01",
    interview_date: "2026-07-10",
    deadline: "2026-06-25",
    description:
      "Lắp ráp, kiểm tra và bảo trì thiết bị y tế chuyên dụng. Đào tạo theo chuẩn IHK Hessen.",
    requirements: ["Tiếng Đức B1", "Cẩn thận, tỉ mỉ"],
    benefits: ["Lương 1.100–1.300 EUR", "Bảo hiểm đầy đủ", "Hỗ trợ chỗ ở"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-14T08:00:00Z",
  },
  {
    id: "j8",
    company_id: "co6",
    company_name: "BMW Group",
    company_logo: "https://logo.clearbit.com/bmw.com",
    title: "Kỹ thuật viên điện tử ô tô",
    slug: "ky-thuat-vien-dien-tu-o-to-bmw",
    occupation: "Cơ điện tử",
    training_type: "Dual",
    city: "Munich",
    state: "Bayern",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT, ưu tiên có nền tảng kỹ thuật",
    monthly_allowance_min: 1180,
    monthly_allowance_max: 1380,
    start_date: "2026-09-01",
    interview_date: "2026-07-15",
    deadline: "2026-06-30",
    description:
      "Đào tạo Ausbildung tại nhà máy BMW Munich. Học viên được làm việc với hệ thống ECU, e-mobility và assembly line hiện đại.",
    requirements: ["Tiếng Đức B1", "Toán/Lý tốt", "Đam mê ô tô"],
    benefits: ["Lương 1.180–1.380 EUR", "Học bổng B2", "Đi lại miễn phí"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-13T08:00:00Z",
  },
  {
    id: "j9",
    company_id: "co2",
    company_name: "Robert Bosch GmbH",
    company_logo: "https://logo.clearbit.com/bosch.com",
    title: "Kỹ thuật viên cơ khí",
    slug: "ky-thuat-vien-co-khi-bosch",
    occupation: "Cơ khí",
    training_type: "Dual",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1100,
    monthly_allowance_max: 1300,
    start_date: "2026-09-01",
    interview_date: "2026-07-20",
    deadline: "2026-07-01",
    description:
      "Chương trình Industriemechaniker tại các nhà máy Bosch khu vực Stuttgart.",
    requirements: ["Tiếng Đức B1", "Sức khỏe tốt", "Có khả năng làm việc nhóm"],
    benefits: ["Lương 1.100–1.300 EUR", "Tăng lương theo năm", "Cơ hội ở lại"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-12T08:00:00Z",
  },
  {
    id: "j10",
    company_id: "co8",
    company_name: "Marriott Hotels Germany",
    company_logo: "https://logo.clearbit.com/marriott.com",
    title: "Đầu bếp (Koch/Köchin)",
    slug: "dau-bep-marriott-frankfurt",
    occupation: "Đầu bếp",
    training_type: "Dual",
    city: "Frankfurt",
    state: "Hessen",
    german_level_required: "B1",
    education_required: "Tốt nghiệp THPT",
    monthly_allowance_min: 1100,
    monthly_allowance_max: 1300,
    start_date: "2026-08-15",
    interview_date: "2026-06-28",
    deadline: "2026-06-12",
    description:
      "Đào tạo đầu bếp chuyên nghiệp tại nhà hàng khách sạn 5 sao Marriott Frankfurt.",
    requirements: ["Tiếng Đức B1", "Đam mê ẩm thực", "Sức khỏe tốt"],
    benefits: ["Lương 1.100–1.300 EUR", "Bữa ăn miễn phí", "Đồng phục"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-11T08:00:00Z",
  },
  {
    id: "j11",
    company_id: "co7",
    company_name: "Charité Berlin",
    company_logo: "https://ui-avatars.com/api/?name=CB&background=ef4444&color=fff",
    title: "Kỹ thuật viên xét nghiệm (MTLA)",
    slug: "ky-thuat-vien-xet-nghiem-charite",
    occupation: "Y tế kỹ thuật",
    training_type: "Schulisch",
    city: "Berlin",
    state: "Berlin",
    german_level_required: "B2",
    education_required: "Tốt nghiệp THPT, ưu tiên có nền tảng sinh học",
    monthly_allowance_min: 950,
    monthly_allowance_max: 1100,
    start_date: "2026-10-01",
    interview_date: "2026-07-25",
    deadline: "2026-07-10",
    description:
      "Chương trình đào tạo MTLA 3 năm tại trường y tế Charité, kết hợp lý thuyết và thực hành phòng lab.",
    requirements: ["Tiếng Đức B2", "Học khá môn Sinh/Hóa"],
    benefits: ["Lương 950–1.100 EUR", "Học phí miễn phí", "Hỗ trợ ký túc xá"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "j12",
    company_id: "co1",
    company_name: "Siemens AG",
    company_logo: "https://logo.clearbit.com/siemens.com",
    title: "Software Developer Trainee",
    slug: "software-developer-siemens",
    occupation: "IT",
    training_type: "Dual",
    city: "Erlangen",
    state: "Bayern",
    german_level_required: "B2",
    education_required: "Tốt nghiệp THPT, có kiến thức lập trình cơ bản",
    monthly_allowance_min: 1300,
    monthly_allowance_max: 1500,
    start_date: "2026-09-01",
    interview_date: "2026-08-01",
    deadline: "2026-07-15",
    description:
      "Chương trình Fachinformatiker với Siemens Mobility. Học viên được tham gia phát triển hệ thống tín hiệu đường sắt thông minh.",
    requirements: ["Tiếng Đức B2", "Lập trình cơ bản (Python/Java)"],
    benefits: ["Lương 1.300–1.500 EUR", "Hỗ trợ nhà ở", "Học bổng C1"],
    status: "open",
    verification_status: "verified",
    is_featured: false,
    created_at: "2026-04-09T08:00:00Z",
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: "p1",
    author_id: "u1",
    author_name: "Nguyễn Minh Anh",
    author_avatar: "https://ui-avatars.com/api/?name=Minh+Anh&background=22d3ee",
    author_role: "student",
    title: "Cho em hỏi ngành điều dưỡng viên thì công ty nào uy tín?",
    content:
      "Em đang phân vân giữa Charité và K&S Gruppe, anh chị nào đã làm rồi cho em xin review thực tế với ạ.",
    category: "Hỏi đáp",
    like_count: 24,
    comment_count: 8,
    status: "approved",
    created_at: "2026-04-24T08:00:00Z",
    tags: ["điều dưỡng", "Charité", "K&S"],
  },
  {
    id: "p2",
    author_id: "u2",
    author_name: "Trần Đức Nam",
    author_avatar: "https://ui-avatars.com/api/?name=Duc+Nam&background=8b5cf6",
    author_role: "student",
    title: "Review phỏng vấn đơn nhà hàng tại Bayern",
    content:
      "Mình vừa phỏng vấn Marriott Munich xong. Câu hỏi xoay quanh động lực, kinh nghiệm phục vụ và case xử lý khách phàn nàn. Cập nhật chi tiết bên trong.",
    category: "Kinh nghiệm",
    like_count: 56,
    comment_count: 19,
    status: "approved",
    created_at: "2026-04-23T15:00:00Z",
    tags: ["phỏng vấn", "nhà hàng"],
  },
  {
    id: "p3",
    author_id: "u3",
    author_name: "Phạm Thị Hương",
    author_avatar: "https://ui-avatars.com/api/?name=Thi+Huong&background=facc15&color=000",
    author_role: "student",
    title: "Checklist hồ sơ trước khi nộp visa Ausbildung",
    content:
      "Mình tổng hợp 23 đầu mục mà các bạn cần chuẩn bị trước khi đi nộp visa. File excel kèm bên dưới.",
    category: "Hồ sơ",
    like_count: 124,
    comment_count: 32,
    status: "approved",
    created_at: "2026-04-22T08:00:00Z",
    tags: ["visa", "hồ sơ"],
  },
  {
    id: "p4",
    author_id: "u4",
    author_name: "Lê Văn Hùng",
    author_avatar: "https://ui-avatars.com/api/?name=Van+Hung&background=22c55e",
    author_role: "student",
    title: "Kinh nghiệm học B1 trong 6 tháng",
    content:
      "Lộ trình của mình: 2 tháng A1, 2 tháng A2, 2 tháng B1. Mỗi ngày học 4 giờ và xem phim Đức 1 giờ.",
    category: "Kinh nghiệm",
    like_count: 87,
    comment_count: 24,
    status: "approved",
    created_at: "2026-04-21T08:00:00Z",
    tags: ["tiếng đức", "B1"],
  },
  {
    id: "p5",
    author_id: "u5",
    author_name: "Ausbildung Hub Admin",
    author_avatar: "https://ui-avatars.com/api/?name=AHV&background=06b6d4",
    author_role: "admin",
    title: "Thông báo: Cập nhật quy trình kiểm duyệt từ tháng 6/2026",
    content:
      "Chúng tôi sẽ rút ngắn thời gian xét duyệt review xuống còn 24 giờ. Vui lòng tham khảo guideline mới đính kèm.",
    category: "Thông báo",
    like_count: 41,
    comment_count: 5,
    status: "approved",
    created_at: "2026-04-20T08:00:00Z",
    tags: ["thông báo"],
  },
  {
    id: "p6",
    author_id: "u6",
    author_name: "Nguyễn Hồng Linh",
    author_avatar: "https://ui-avatars.com/api/?name=Hong+Linh&background=ef4444",
    author_role: "student",
    title: "Tìm bạn cùng nhà tại Berlin tháng 9",
    content:
      "Mình sẽ qua Berlin học Ausbildung Charité từ tháng 9. Tìm 1-2 bạn share apartment khu Mitte.",
    category: "Việc làm",
    like_count: 18,
    comment_count: 11,
    status: "approved",
    created_at: "2026-04-19T08:00:00Z",
    tags: ["nhà ở", "Berlin"],
  },
  {
    id: "p7",
    author_id: "u7",
    author_name: "Trần Thị Mai",
    author_avatar: "https://ui-avatars.com/api/?name=Thi+Mai&background=8b5cf6",
    author_role: "student",
    title: "Tài liệu luyện thi B1 miễn phí 2026",
    content:
      "Sưu tầm 30 đề thi B1 Goethe + ÖSD chuẩn 2026, mọi người tải về luyện nha.",
    category: "Hồ sơ",
    like_count: 142,
    comment_count: 28,
    status: "approved",
    created_at: "2026-04-18T08:00:00Z",
    tags: ["B1", "luyện thi"],
  },
  {
    id: "p8",
    author_id: "u8",
    author_name: "Lê Quang Huy",
    author_avatar: "https://ui-avatars.com/api/?name=Quang+Huy&background=3b82f6",
    author_role: "student",
    title: "Có nên học B2 trước khi đi Đức?",
    content:
      "Mình đang phân vân nên đi với B1 hay đợi xong B2 mới đi. Anh chị tư vấn giúp ạ.",
    category: "Hỏi đáp",
    like_count: 32,
    comment_count: 15,
    status: "approved",
    created_at: "2026-04-17T08:00:00Z",
    tags: ["B1", "B2"],
  },
  {
    id: "p9",
    author_id: "u9",
    author_name: "Phạm Đăng Khoa",
    author_avatar: "https://ui-avatars.com/api/?name=Dang+Khoa&background=22c55e",
    author_role: "student",
    title: "Review trung tâm DeutschAkademie Hà Nội sau 8 tháng",
    content:
      "Mình học xong B1 tại đây, cảm nhận chung khá tốt: giáo viên nhiệt tình, lớp ít người, hỗ trợ visa kỹ.",
    category: "Kinh nghiệm",
    like_count: 67,
    comment_count: 21,
    status: "approved",
    created_at: "2026-04-16T08:00:00Z",
    tags: ["DeutschAkademie", "review"],
  },
  {
    id: "p10",
    author_id: "u10",
    author_name: "Vũ Hoàng Nam",
    author_avatar: "https://ui-avatars.com/api/?name=Hoang+Nam&background=facc15&color=000",
    author_role: "student",
    title: "Kinh nghiệm xin visa tại lãnh sự quán Đức",
    content:
      "Lịch hẹn bao lâu, hồ sơ cần gì, phỏng vấn ra sao — mình chia sẻ chi tiết.",
    category: "Hồ sơ",
    like_count: 95,
    comment_count: 26,
    status: "approved",
    created_at: "2026-04-15T08:00:00Z",
    tags: ["visa", "lãnh sự"],
  },
];

export const verificationRequests: VerificationRequest[] = [
  {
    id: "v1",
    requester_id: "c1",
    requester_name: "DeutschAkademie Hà Nội",
    entity_type: "center",
    entity_id: "c1",
    entity_name: "DeutschAkademie Hà Nội",
    status: "approved",
    submitted_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "v2",
    requester_id: "c6",
    requester_name: "Berliner Tor Sài Gòn",
    entity_type: "center",
    entity_id: "c6",
    entity_name: "Berliner Tor Sài Gòn",
    status: "pending",
    submitted_at: "2026-04-22T08:00:00Z",
  },
  {
    id: "v3",
    requester_id: "co1",
    requester_name: "Siemens AG",
    entity_type: "company",
    entity_id: "co1",
    entity_name: "Siemens AG",
    status: "approved",
    submitted_at: "2026-03-15T08:00:00Z",
  },
];

export const reportFlags: ReportFlag[] = [
  {
    id: "rf1",
    reporter_id: "u1",
    reporter_name: "Nguyễn Minh Anh",
    target_type: "post",
    target_id: "p1287",
    target_label: "Post #1287 — quảng cáo trá hình",
    reason: "Quảng cáo / Spam",
    status: "open",
    created_at: "2026-04-24T08:00:00Z",
  },
  {
    id: "rf2",
    reporter_id: "u2",
    reporter_name: "Trần Đức Nam",
    target_type: "review",
    target_id: "r1287",
    target_label: "Review #1287 — Thông tin sai",
    reason: "Thông tin sai sự thật",
    status: "open",
    created_at: "2026-04-23T08:00:00Z",
  },
  {
    id: "rf3",
    reporter_id: "u3",
    reporter_name: "Phạm Thị Hương",
    target_type: "post",
    target_id: "p1289",
    target_label: "Post #1289 — Lừa đảo",
    reason: "Lừa đảo",
    status: "open",
    created_at: "2026-04-22T08:00:00Z",
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "basic",
    name: "Basic",
    price: "Miễn phí",
    audience: "Học viên & cá nhân",
    description: "Khám phá tin tức, trung tâm và việc làm cơ bản.",
    features: [
      "Xem tất cả tin tức",
      "Tìm kiếm trung tâm và việc làm",
      "Tham gia cộng đồng giới hạn 5 bài/tháng",
      "Lưu tối đa 10 việc làm",
    ],
    cta: "Đăng ký miễn phí",
  },
  {
    id: "starter",
    name: "Starter",
    price: "499.000đ / tháng",
    audience: "Trung tâm nhỏ",
    description: "Cho trung tâm tiếng Đức mới khởi động.",
    features: [
      "Hồ sơ trung tâm tùy chỉnh",
      "Đăng tối đa 5 lớp học",
      "Nhận lead cơ bản",
      "Hỗ trợ qua email",
    ],
    cta: "Dùng thử 7 ngày",
  },
  {
    id: "professional",
    name: "Professional",
    price: "1.299.000đ / tháng",
    audience: "Trung tâm chuyên nghiệp",
    description: "Phổ biến nhất — cho trung tâm có quy mô.",
    features: [
      "Tất cả tính năng Starter",
      "Featured listing trên trang chủ",
      "Lead dashboard + analytics",
      "Unlimited posting",
      "Verified badge request",
      "Hỗ trợ ưu tiên 24/7",
    ],
    highlight: true,
    cta: "Dùng thử 7 ngày",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Liên hệ",
    audience: "Agency & employer lớn",
    description: "Tùy chỉnh sâu cho tập đoàn và nhóm tuyển dụng quốc tế.",
    features: [
      "Custom workflow",
      "API / data export",
      "SSO + role management",
      "Dedicated CSM",
      "SLA hợp đồng",
    ],
    cta: "Liên hệ tư vấn",
  },
];

// Quick lookups
export const findCenter = (slug: string) => centers.find((c) => c.slug === slug);
export const findJob = (slug: string) => jobOrders.find((j) => j.slug === slug);
export const findArticle = (slug: string) => articles.find((a) => a.slug === slug);
export const findCompany = (slug: string) => companies.find((c) => c.slug === slug);
