-- ===================================================================
-- 0004_user_verification_storage.sql
--
-- 1. Creates the private Supabase Storage bucket
--    `verification-evidence-private` used by the user-verification
--    flow (/docs/user-verification-flow.md §3, /docs/rls-policy.md
--    §16.2).
-- 2. Adds RLS policies on `storage.objects` so:
--      * users can upload / read / replace / delete files only under
--        their own path prefix `user/<auth.uid()>/verification/...`,
--      * moderators and admins can read every file in the bucket
--        through the admin UI (signed URLs only — generated server-side),
--      * no anonymous access is ever permitted.
-- 3. Updates `handle_new_user` so that a `self_declared_stage` value
--    captured during registration is persisted to
--    `profiles.self_declared_stage` (defaults to 'exploring').
--
-- Idempotent — safe to re-apply.
-- ===================================================================


-- ===================================================================
-- 1. Private bucket
-- ===================================================================
-- `public = false` ensures Supabase will not generate public URLs.
-- The bucket name matches /docs/rls-policy.md §16.2.
insert into storage.buckets (id, name, public)
values ('verification-evidence-private', 'verification-evidence-private', false)
on conflict (id) do update
  set public = excluded.public;


-- ===================================================================
-- 2. RLS policies on storage.objects, scoped to this bucket
-- -------------------------------------------------------------------
-- Path layout (enforced in policy):
--   user/<auth.uid()>/verification/<verification_id>/<filename>
-- name is split on '/' by storage.foldername(name); index 1 = 'user',
-- index 2 = the user's UUID, index 3 = 'verification'.
-- ===================================================================
alter table storage.objects enable row level security;

-- Users can upload only into their own folder.
drop policy if exists "Users can upload own verification evidence"
  on storage.objects;
create policy "Users can upload own verification evidence"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'user'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[3] = 'verification'
  );

-- Users can read only their own files. Admin UI uses signed URLs
-- generated by the service role on the server, which bypass RLS, so
-- a moderator/admin SELECT policy here is intentionally NOT added.
drop policy if exists "Users can read own verification evidence"
  on storage.objects;
create policy "Users can read own verification evidence"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'user'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[3] = 'verification'
  );

-- Users can replace / delete their own evidence (e.g. before review,
-- when status is still pending or need_more_info). The DB-level RLS
-- on user_verifications.status is the authoritative gate; storage just
-- mirrors path ownership.
drop policy if exists "Users can update own verification evidence"
  on storage.objects;
create policy "Users can update own verification evidence"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'user'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[3] = 'verification'
  )
  with check (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'user'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[3] = 'verification'
  );

drop policy if exists "Users can delete own verification evidence"
  on storage.objects;
create policy "Users can delete own verification evidence"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'user'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[3] = 'verification'
  );


-- ===================================================================
-- 3. Refresh handle_new_user to capture self_declared_stage
-- -------------------------------------------------------------------
-- The signup form now collects the user's self-declared journey
-- stage. Store it on the new profiles row so the dashboard reflects
-- the user's choice immediately. Falls back to 'exploring' (the table
-- default) for any value not in the allow-list.
-- ===================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  meta_role           text;
  meta_full_name      text;
  meta_self_stage     text;
  resolved_stage      text;
begin
  meta_role        := nullif(new.raw_user_meta_data ->> 'role', '');
  meta_full_name   := nullif(new.raw_user_meta_data ->> 'full_name', '');
  meta_self_stage  := nullif(new.raw_user_meta_data ->> 'self_declared_stage', '');

  if meta_self_stage in (
    'exploring','studying_german','studying_at_center','completed_center_course',
    'interviewed','contract_signed','visa_process','in_germany',
    'doing_ausbildung','alumni'
  ) then
    resolved_stage := meta_self_stage;
  else
    resolved_stage := 'exploring';
  end if;

  insert into public.profiles (id, email, full_name, role, self_declared_stage)
  values (
    new.id,
    new.email,
    meta_full_name,
    case
      when meta_role in ('student', 'center_admin', 'employer_admin')
        then meta_role
      else 'student'
    end,
    resolved_stage
  )
  on conflict (id) do nothing;

  return new;
end;
$$;
