-- ===================================================================
-- 0005_organization_verification_storage.sql
--
-- Adds RLS policies on `storage.objects` for organization-scoped
-- verification evidence stored in the existing private bucket
-- `verification-evidence-private` (created in 0004). User-scoped
-- evidence policies from 0004 remain untouched.
--
-- Path layout enforced by these policies:
--   org/<organization_id>/verification/<verification_id>/<filename>
--
-- name is split on '/' by storage.foldername(name); index 1 = 'org',
-- index 2 = the organization's UUID, index 3 = 'verification'.
--
-- Access rules (mirrors /docs/rls-policy.md §16.2):
--   * Active members of the organization can upload / read / replace
--     / delete evidence under that organization's prefix.
--   * Admin / moderator staff read evidence ONLY through server-side
--     signed URLs generated by the service role (no SELECT policy is
--     added here for staff — it is intentional).
--   * No anonymous access.
--
-- /docs/audit-log-rules.md §5.4 expects every staff view to be
-- audited; that audit log is written by the
-- /admin/organization-verifications/[id]/file route handler, not by
-- a storage policy.
--
-- Idempotent — safe to re-apply.
-- ===================================================================

-- The bucket itself was created in 0004 and is private (public=false).
-- We re-assert that here just to make this migration self-contained
-- if it is ever applied out of order against a fresh database.
insert into storage.buckets (id, name, public)
values ('verification-evidence-private', 'verification-evidence-private', false)
on conflict (id) do update
  set public = excluded.public;

alter table storage.objects enable row level security;


-- -------------------------------------------------------------------
-- Helper: caller is an active member of the organization referenced
-- by an `org/<org_id>/verification/...` path.
--
-- We can't call public.is_org_member directly inside a storage policy
-- because (a) it dereferences auth.uid() (which is fine) but (b) the
-- second arg would need to come from `(storage.foldername(name))[2]`
-- which is text, not uuid. We add a small SECURITY DEFINER wrapper
-- that does the cast safely.
-- -------------------------------------------------------------------
create or replace function public.is_org_member_text(org_id_text text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  org_uuid uuid;
begin
  -- Reject malformed UUIDs without raising — RLS policies must
  -- evaluate to false (not error) on a non-matching path.
  begin
    org_uuid := org_id_text::uuid;
  exception when others then
    return false;
  end;
  return public.is_org_member(org_uuid);
end;
$$;

revoke all on function public.is_org_member_text(text) from public;
grant execute on function public.is_org_member_text(text)
  to authenticated, anon;


-- -------------------------------------------------------------------
-- INSERT: org members can upload evidence into their org's folder.
-- -------------------------------------------------------------------
drop policy if exists "Org members can upload organization verification evidence"
  on storage.objects;
create policy "Org members can upload organization verification evidence"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'org'
    and (storage.foldername(name))[3] = 'verification'
    and public.is_org_member_text((storage.foldername(name))[2])
  );


-- -------------------------------------------------------------------
-- SELECT: org members can read evidence for their own org. Other
-- orgs and anonymous users are blocked. Staff use server-side
-- signed URLs (service-role bypasses RLS).
-- -------------------------------------------------------------------
drop policy if exists "Org members can read organization verification evidence"
  on storage.objects;
create policy "Org members can read organization verification evidence"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'org'
    and (storage.foldername(name))[3] = 'verification'
    and public.is_org_member_text((storage.foldername(name))[2])
  );


-- -------------------------------------------------------------------
-- UPDATE: org members can replace their own org's evidence. The
-- DB-level RLS on organization_verifications.status is the
-- authoritative gate for whether the request is still mutable;
-- storage just mirrors path ownership.
-- -------------------------------------------------------------------
drop policy if exists "Org members can update organization verification evidence"
  on storage.objects;
create policy "Org members can update organization verification evidence"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'org'
    and (storage.foldername(name))[3] = 'verification'
    and public.is_org_member_text((storage.foldername(name))[2])
  )
  with check (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'org'
    and (storage.foldername(name))[3] = 'verification'
    and public.is_org_member_text((storage.foldername(name))[2])
  );


-- -------------------------------------------------------------------
-- DELETE: org members can delete their own org's evidence (e.g.
-- before review while status is still pending or need_more_info).
-- -------------------------------------------------------------------
drop policy if exists "Org members can delete organization verification evidence"
  on storage.objects;
create policy "Org members can delete organization verification evidence"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'verification-evidence-private'
    and (storage.foldername(name))[1] = 'org'
    and (storage.foldername(name))[3] = 'verification'
    and public.is_org_member_text((storage.foldername(name))[2])
  );
